# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHBoxLayout, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTextEdit, QToolBar,
    QVBoxLayout, QWidget)
import Ressources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(923, 365)
        self.action_Connect = QAction(MainWindow)
        self.action_Connect.setObjectName(u"action_Connect")
        icon = QIcon()
        icon.addFile(u":/images/connect.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_Connect.setIcon(icon)
        self.action_Disconnect = QAction(MainWindow)
        self.action_Disconnect.setObjectName(u"action_Disconnect")
        icon1 = QIcon()
        icon1.addFile(u":/images/disconnect.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_Disconnect.setIcon(icon1)
        self.action_Clear_Log = QAction(MainWindow)
        self.action_Clear_Log.setObjectName(u"action_Clear_Log")
        icon2 = QIcon()
        icon2.addFile(u":/images/clear.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_Clear_Log.setIcon(icon2)
        self.action_Quit = QAction(MainWindow)
        self.action_Quit.setObjectName(u"action_Quit")
        icon3 = QIcon()
        icon3.addFile(u":/images/application-exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_Quit.setIcon(icon3)
        self.action_Refresh = QAction(MainWindow)
        self.action_Refresh.setObjectName(u"action_Refresh")
        icon4 = QIcon()
        icon4.addFile(u":/images/refresh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_Refresh.setIcon(icon4)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label)

        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")

        self.verticalLayout.addWidget(self.textEdit)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout_2.addWidget(self.label_2)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")

        self.horizontalLayout.addWidget(self.label_4)

        self.comboBox_trame_1 = QComboBox(self.centralwidget)
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.addItem("")
        self.comboBox_trame_1.setObjectName(u"comboBox_trame_1")

        self.horizontalLayout.addWidget(self.comboBox_trame_1)

        self.comboBox_trame_2 = QComboBox(self.centralwidget)
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.addItem("")
        self.comboBox_trame_2.setObjectName(u"comboBox_trame_2")

        self.horizontalLayout.addWidget(self.comboBox_trame_2)

        self.comboBox_trame_3 = QComboBox(self.centralwidget)
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.addItem("")
        self.comboBox_trame_3.setObjectName(u"comboBox_trame_3")

        self.horizontalLayout.addWidget(self.comboBox_trame_3)

        self.comboBox_trame_4 = QComboBox(self.centralwidget)
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.addItem("")
        self.comboBox_trame_4.setObjectName(u"comboBox_trame_4")

        self.horizontalLayout.addWidget(self.comboBox_trame_4)

        self.comboBox_trame_5 = QComboBox(self.centralwidget)
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.addItem("")
        self.comboBox_trame_5.setObjectName(u"comboBox_trame_5")

        self.horizontalLayout.addWidget(self.comboBox_trame_5)

        self.comboBox_trame_6 = QComboBox(self.centralwidget)
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.addItem("")
        self.comboBox_trame_6.setObjectName(u"comboBox_trame_6")

        self.horizontalLayout.addWidget(self.comboBox_trame_6)

        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")

        self.horizontalLayout.addWidget(self.label_3)


        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.sendButton_trame_brute = QPushButton(self.centralwidget)
        self.sendButton_trame_brute.setObjectName(u"sendButton_trame_brute")

        self.horizontalLayout_2.addWidget(self.sendButton_trame_brute)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 923, 26))
        self.menuFichiers = QMenu(self.menuBar)
        self.menuFichiers.setObjectName(u"menuFichiers")
        self.menuPort_COM = QMenu(self.menuBar)
        self.menuPort_COM.setObjectName(u"menuPort_COM")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menuBar.addAction(self.menuFichiers.menuAction())
        self.menuBar.addAction(self.menuPort_COM.menuAction())
        self.menuFichiers.addAction(self.action_Quit)
        self.menuPort_COM.addAction(self.action_Connect)
        self.menuPort_COM.addAction(self.action_Disconnect)
        self.toolBar.addAction(self.action_Connect)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Disconnect)
        self.toolBar.addAction(self.action_Clear_Log)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Refresh)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_Connect.setText(QCoreApplication.translate("MainWindow", u"&Connect", None))
#if QT_CONFIG(tooltip)
        self.action_Connect.setToolTip(QCoreApplication.translate("MainWindow", u"Connect", None))
#endif // QT_CONFIG(tooltip)
        self.action_Disconnect.setText(QCoreApplication.translate("MainWindow", u"&Disconnect", None))
        self.action_Clear_Log.setText(QCoreApplication.translate("MainWindow", u"&Clear & Log", None))
#if QT_CONFIG(tooltip)
        self.action_Clear_Log.setToolTip(QCoreApplication.translate("MainWindow", u"Clear &  Log", None))
#endif // QT_CONFIG(tooltip)
        self.action_Quit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
        self.action_Refresh.setText(QCoreApplication.translate("MainWindow", u"&Refresh", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Banc de test Module X Voies", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Envoyer une trame en brut", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.comboBox_trame_1.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_trame_1.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_trame_1.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_trame_1.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_trame_1.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_trame_1.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_trame_1.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_trame_1.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_trame_1.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_trame_1.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_trame_1.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_trame_1.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_trame_1.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_trame_1.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_trame_1.setItemText(14, QCoreApplication.translate("MainWindow", u"E", None))
        self.comboBox_trame_1.setItemText(15, QCoreApplication.translate("MainWindow", u"F", None))

        self.comboBox_trame_2.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_trame_2.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_trame_2.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_trame_2.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_trame_2.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_trame_2.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_trame_2.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_trame_2.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_trame_2.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_trame_2.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_trame_2.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_trame_2.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_trame_2.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_trame_2.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_trame_2.setItemText(14, QCoreApplication.translate("MainWindow", u"E", None))
        self.comboBox_trame_2.setItemText(15, QCoreApplication.translate("MainWindow", u"F", None))

        self.comboBox_trame_3.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_trame_3.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_trame_3.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_trame_3.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_trame_3.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_trame_3.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_trame_3.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_trame_3.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_trame_3.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_trame_3.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_trame_3.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_trame_3.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_trame_3.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_trame_3.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_trame_3.setItemText(14, QCoreApplication.translate("MainWindow", u"E", None))
        self.comboBox_trame_3.setItemText(15, QCoreApplication.translate("MainWindow", u"F", None))

        self.comboBox_trame_4.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_trame_4.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_trame_4.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_trame_4.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_trame_4.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_trame_4.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_trame_4.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_trame_4.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_trame_4.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_trame_4.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_trame_4.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_trame_4.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_trame_4.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_trame_4.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_trame_4.setItemText(14, QCoreApplication.translate("MainWindow", u"E", None))
        self.comboBox_trame_4.setItemText(15, QCoreApplication.translate("MainWindow", u"F", None))

        self.comboBox_trame_5.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_trame_5.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_trame_5.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_trame_5.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_trame_5.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_trame_5.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_trame_5.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_trame_5.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_trame_5.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_trame_5.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_trame_5.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_trame_5.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_trame_5.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_trame_5.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_trame_5.setItemText(14, QCoreApplication.translate("MainWindow", u"E", None))
        self.comboBox_trame_5.setItemText(15, QCoreApplication.translate("MainWindow", u"F", None))

        self.comboBox_trame_6.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_trame_6.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_trame_6.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_trame_6.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_trame_6.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_trame_6.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_trame_6.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_trame_6.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_trame_6.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_trame_6.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_trame_6.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_trame_6.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_trame_6.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_trame_6.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_trame_6.setItemText(14, QCoreApplication.translate("MainWindow", u"E", None))
        self.comboBox_trame_6.setItemText(15, QCoreApplication.translate("MainWindow", u"F", None))

        self.label_3.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.sendButton_trame_brute.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.menuFichiers.setTitle(QCoreApplication.translate("MainWindow", u"Fichiers", None))
        self.menuPort_COM.setTitle(QCoreApplication.translate("MainWindow", u"Port COM", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

